# Generated by Django 3.1.7 on 2021-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_auto_20210512_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='upload',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
