# Generated by Django 3.1.7 on 2021-05-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_auto_20210512_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
