# Generated by Django 3.1.7 on 2021-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('assigned_date', models.DateField()),
                ('return_date', models.DateField()),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
