# Generated by Django 3.1.7 on 2021-03-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_assets',
        ),
    ]
