# Generated by Django 3.1.7 on 2021-03-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(blank=True, max_length=45)),
                ('asset_tag', models.CharField(blank=True, max_length=45)),
                ('table_name', models.CharField(max_length=45)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('assigned_date', models.DateField()),
                ('return_date', models.DateField()),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField()),
                ('asset_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.asset_types')),
            ],
        ),
        migrations.CreateModel(
            name='asset_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('asset_tag_number', models.CharField(blank=True, max_length=45, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=45, null=True)),
                ('model', models.CharField(blank=True, max_length=45, null=True)),
                ('cpu', models.CharField(blank=True, max_length=45, null=True)),
                ('ram', models.CharField(blank=True, max_length=45, null=True)),
                ('hdd', models.CharField(blank=True, max_length=45, null=True)),
                ('os', models.CharField(blank=True, max_length=45, null=True)),
                ('screen', models.CharField(blank=True, max_length=45, null=True)),
                ('cd_drive', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=45, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=45, null=True)),
                ('purchase', models.DateField()),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.IntegerField()),
                ('asset_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='manager.asset_types')),
            ],
        ),
    ]
