# Generated by Django 3.1.7 on 2021-03-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset_types',
            name='asset_type',
        ),
        migrations.AlterField(
            model_name='asset_name',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset_types',
            name='table_name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
