# Generated by Django 3.1.7 on 2021-03-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210318_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_assets',
            name='asset_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.asset_types'),
        ),
    ]
